'use strict';

module.exports =
`

insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('mana');
insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('force');
insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('vitesse');
insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('defense');
insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('attaque');
insert into CARACTERISTIQUE(NOM_CARACTERISTIQUE) values ('soin');


insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Attaque un adversaire', 'sort', 'Justicier', 'rouge', 'https://i.pinimg.com/originals/ee/2d/64/ee2d6458d09ed10e1be0e4476f4ac658.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Défend le château', 'défense', 'Défenseur', 'vert', 'https://images.saatchiart.com/saatchi/870022/art/3454893/2524780-ISDBAXTE-7.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Sacrifie une entité', 'sacrifice', 'Sataniste', 'rouge', 'https://pm1.narvii.com/6991/ea1baf640f021755119862f29850e8f4e1f0f4bbr1-1344-2048v2_hq.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Invoque Pikachu', 'créature', 'Pikachu', 'bleu', 'https://i.pinimg.com/originals/f5/1d/08/f51d08be05919290355ac004cdd5c2d6.png');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Envoie une entité au cimetière', 'movement', 'Fossoyeur', 'jaune', 'https://i.pinimg.com/originals/36/c1/94/36c19446d136cae841ca529bd48f6648.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Guérit une entité', 'sort', 'Guérison', 'vert', 'https://i.pinimg.com/originals/e0/40/fb/e040fb8ba1da972b9e878425b30166a1.png');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Consomme défense', 'sort', 'Jinzo', 'gris', 'https://thumbs.dreamstime.com/b/joust-victory-medieval-knights-participating-one-them-wins-powerful-impact-breaking-his-weapon-his-opponent-s-97950517.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Détruit une entité', 'destruction', 'Polier', 'gris', 'https://66.media.tumblr.com/6c9391745d9455d18c9914199ec15a19/tumblr_pxoe9y7TR51qm1bz4o1_400.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Créé défense', 'défense', 'Pilgrim', 'gris', 'https://d1s0ws440m13mk.cloudfront.net/original/3X/4/8/484c96d9d0dfd28a8e818e0574c0287202a2e222.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('Réssucite une entité', 'défense', 'Aumonier', 'blanc', 'https://i.pinimg.com/originals/77/a1/26/77a12608b4081a4d15bb8d16d53fd49a.jpg');
insert into CARTE(DESCRIPTION_CARTE, TYPE_CARTE, TITRE_CARTE, FAMILLE_CARTE, IMAGE_CARTE) values ('GLOUGLOU', 'attaque', 'Dindon', 'Oiseau', 'https://www.mypokecard.com/fr/Galerie/my/galery/skd7WRMFnwCd.jpg');


insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(1, 5, 20);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(1, 4, 5);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(2, 4, 15);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(2, 2, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(3, 4, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(3, 2, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(4, 3, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(4, 5, 20);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(5, 2, 15);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(5, 5, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(6, 6, 20);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(6, 4, 5);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(7, 4, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(7, 5, 10);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(8, 5, 20);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(8, 2, 5);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(10, 6, 20);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(10, 4, 5);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(11, 3, 999);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(11, 4, 999);
insert into CARACTERISE_PAR(NUMERO_CARTE, NUMERO_CARACTERISTIQUE, NIVEAU) VALUES(11, 5, 999);

delete from CARACTERISE_PAR where NUMERO_CARTE=9 and NUMERO_CARACTERISTIQUE=1;

insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Mirande', 'Julien', 'zayrrox');
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Herrero', 'Victor', 'ender');
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Germon', 'Paul', 'le boss');
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Jacobi', 'Otavio', 'bidule');
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Piere', 'Pedro', 'collectionneur');
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, PSEUDONYME) values('Marchand', 'Coraline', 'pietra');



insert into DECK(NOM_DECK) values ('Le grand Pikachu');
insert into DECK(NOM_DECK) values ('Sort Noir');
insert into DECK(NOM_DECK) values ('Vampire');
insert into DECK(NOM_DECK) values ('Medieval');
insert into DECK(NOM_DECK) values ('Deck ultime');


insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (1, 1);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (2, 1);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (4, 1);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (6, 1);

insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (3, 2);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (5, 2);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (8, 2);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (10, 2);

insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (5, 3);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (6, 3);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (7, 3);

insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (1, 4);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (2, 4);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (3, 4);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (8, 4);

insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (1, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (2, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (3, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (4, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (5, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (6, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (7, 5);
insert into COMPOSITION_DECK(NUMERO_CARTE, NUMERO_DECK) values (8, 5);

insert into POSSEDE_PAR(NUMERO_JOUEUR, NUMERO_DECK) values (1, 3);
insert into POSSEDE_PAR(NUMERO_JOUEUR, NUMERO_DECK) values (2, 2);
insert into POSSEDE_PAR(NUMERO_JOUEUR, NUMERO_DECK) values (3, 4);
insert into POSSEDE_PAR(NUMERO_JOUEUR, NUMERO_DECK) values (4, 1);


insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (1, 'Bordeaux', '2018-12-21', 'double elimination', 'le boss', true, 1, 4);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (1, 'Bordeaux', '2018-12-21', 'double elimination', 'zayrrox', false, 3, 2);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (2, 'Talence', '2019-11-29', 'toutes rondes', 'zayrrox', true, 2, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (2, 'Talence', '2019-11-29', 'toutes rondes', 'ender', false, 1, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (3, 'Porto Alegre', '2018-07-08', 'double elimination', 'mucilera', false, 4, 3);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (4, 'Talence', '1998-07-03', 'toutes rondes', 'bidule', true, 1, 5);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (4, 'Talence', '1998-07-03', 'toutes rondes', 'zayrrox', false, 4, 2);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (5, 'London', '2015-09-27', 'toutes rondes', 'bidule', false, 3, 2);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (5, 'London', '2015-09-27', 'toutes rondes', 'le boss', true, 4, 3);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (6, 'Talence', '2018-06-11', 'toutes rondes', 'zayrrox', false, 2, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (6, 'Talence', '2018-06-11', 'toutes rondes', 'ender', true, 1, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (7, 'Boston', '2018-07-08', 'double elimination', 'morbious', true, 2, 5);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (8, 'Paris', '2016-05-06', 'toutes rondes', 'le boss', true, 4, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (8, 'Paris', '2016-05-06', 'toutes rondes', 'bidule', false, 3, 2);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (9, 'Amsterdam', '2013-04-20', 'toutes rondes', 'zayrrox', false, 2, 1);
insert into PARTIE(NUMERO_PARTIE, LIEU_PARTIE, DATE_PARTIE, TYPE_TOURNOI, PSEUDONYME_ADVERSAIRE, RESULTAT, NUMERO_JOUEUR, NUMERO_DECK)
values (9, 'Amsterdam', '2013-04-20', 'toutes rondes', 'ender', true, 1, 1);



insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 1);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 1);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 1);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 1);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 1);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 2);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 2);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 2);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 2);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 2);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 3);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 3);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 3);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 3);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 3);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 4);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 4);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 4);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 4);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 4);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 5);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 5);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 5);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 5);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 5);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 6);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 6);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 6);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 6);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 6);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 7);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 7);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 7);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 7);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 7);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 8);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 8);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 8);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 8);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 8);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 9);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 9);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 9);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 9);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 9);

insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '1990-01-01', 500, 2, 'basique', 10);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2000-01-01', 200, 5, 'argent', 10);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2005-05-01', 20, 50, 'doré', 10);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (1, '2010-12-01', 3, 500, 'brillant', 10);
insert into EXEMPLAIRE(VERSION, DATE_IMPRESSION, TIRAGE, COTE, RENDU, NUMERO_CARTE) values (2, '2015-01-01', 1, 5000, 'brillant', 10);


insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (10, '1992-12-31', 'Achat neuf', 2.5, '1997-07-25', 'Tournoi', 0, 1, 21);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (32, '2015-12-27', 'Occasion', 4, null, null, null, 1, 42);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (79, '2018-11-26', 'Achat neuf', 50, null, null, null, 1, 28);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (88, '2015-10-24', 'Achat neuf', 7, null, null, null, 1, 32);

insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (51, '1997-07-20', 'Occasion', 1, null, null, null, 2, 11);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (92, '2017-10-10', 'Achat neuf', 2, null, null, null, 2, 23);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (96, '2018-12-20', 'Tournoi', 0, null, null, null, 2, 39);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (86, '2018-12-20', 'Tournoi', 0, null, null, null, 2, 47);

insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (87, '2019-12-07', 'Achat neuf', 35.99, null, null, null, 3, 3);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (98, '2016-01-20', 'Tournoi', 0, null, null, null, 3, 14);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (93, '2015-01-01', 'Tournoi', 0, null, null, null, 3, 10);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (78, '2016-08-14', 'Tournoi', 0, null, null, null, 3, 38);

insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (64, '2016-11-20', 'Occasion', 3, null, null, null, 4, 2);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (75, '2018-03-24', 'Achat neuf', 45, null, null, null, 4, 18);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (97, '2017-05-05', 'Achat neuf', 600, null, null, null, 4, 30);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (48, '2016-04-05', 'Achat neuf', 1, '2016-11-11', 'Vente', '20', 4, 6);

insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (98, '2017-09-20', 'Achat neuf', 8000, null, null, null, 5, 50);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (100, '2015-08-21', 'Achat neuf', 1200, null, null, null, 5, 49);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (100, '2015-01-02', 'Achat neuf', 10000, null, null, null, 5, 30);
insert into PROPRIETE (ETAT_PROPRIETE, DATE_ACQUISITION, MODE_ACQUISITION, PRIX_ACQUISITION, DATE_PERTE, MODE_PERTE, PRIX_VENTE, NUMERO_JOUEUR, NUMERO_EXEMPLAIRE)
values (100, '2016-01-02', 'Achat neuf', 12000, null, null, null, 5, 40);






`;
